version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@4.9.3

executors:
  app-executor:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/repo

aliases:
  - &show-current-branch
    run:  
      name: Show Current Branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys: 
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run: 
      name: Install Dependencies
      command: |
        mkdir -p artifacts
        npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json"}}


jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch
      - *restore-cache
      - *install-dependencies
      - *save-cache

  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch
      - *restore-cache
      - run:
          name: Run Linting
          command: npm run lint

  prettify:
    executor: app-executor
    steps: 
      - checkout
      - *show-current-branch
      - *restore-cache
      - run:
          name: Run Prettier
          command: npm run format 
 
workflows:
    build:
      jobs:
        - build
        - linting:
            requires:
              - build
            filters:
              branches:
                only:
                  - develop
        - prettify:
            requires:
              - build
            filters:
              branches:
                only:
                  - develop
